### ISSUE TITLE
How to add multiple groups? - WordPress role to Azure AD group map

### ISSUE THREAD

**Issue by richthomsen** [psignoret/aad-sso-wordpress#68] opened 2016-03-18 13:19 UTC
I've setup the latest version but not sure how to enter multiple groups.  How or can the plugin setup accommodate multiple groups for the same role (eg. 2 groups both have administrator access).

**Comment by psignoret** [comment] 2016-03-18 15:44
The plugin only supports one group, at the moment. What you can do is create a new group (e.g. "WordPress admins") and add both of your groups to that one.

(In other words, this plugin does work with transitive group memberships.)

**Comment by richthomsen** [comment] 2016-03-18 20:20
It would be great to be able to add multiple groups with a comma.  Where do these settings get stored now?  Is there a file I can edit to replicate what we did with the original Settings.json?

**Comment by psignoret** [comment] 2016-03-29 01:48
(Sorry about the late response here.)

The settings are now stored in the WordPress database, which is about a million times better (more secure, for one) than the JSON file lying around. I strongly recommend against trying to edit the settings in the database directly--consider this unsupported, as I'm entirely unsure what the behavior would be.

However, you questions does bring up that fact that with the Settings.json file, you _could_ set multiple groups for one WordPress role. This was entirely unintended but since it _was_ possible, I'll treat this as a bug (a regression). Should be fixed (i.e. you'll be able to add multiple groups) by the end of the week.

**Comment by richthomsen** [comment] 2016-04-05 18:52
It would be great to have the multi-group capability.  Our processes for adding new groups are very slow and WordPress efforts are generally focused on fast results.  Thanks!

**Comment by psignoret** [comment] 2016-04-05 20:05
I just pushed an update here to GitHub that allows you to provide comma-separated list of group object IDs, instead of just one. (The UI and the documentation doesn't mention this yet, but it works.) Let me know if you have any issues.

**Comment by bradkovach** [comment] 2016-04-05 22:15
Would it be beneficial to add JS to the UI allowing for more than group
object ID per WordPress role?

On Tue, Apr 5, 2016 at 2:07 PM, Philippe Signoret <notifications@github.com>
wrote:

> I just pushed an update here to GitHub that allows you to provide
> comma-separated list of group object IDs, instead of just one. (The UI and
> the documentation doesn't mention this yet, but it works.) Let me know if
> you have any issues.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/psignoret/aad-sso-wordpress/issues/68#issuecomment-205970880>
>



-- 
Brad Kovach
https://bradkovach.com

PGP key available at https://bradkovach.com/pgp
If you need/want to send me an encrypted message, visit
https://bradkovach.com/message

**Comment by psignoret** [comment] 2016-04-06 02:59
@bradkovach I'm working on #9, which will continue support for multiple groups per role.

@richthomsen I'm closing the issue, but feel free to reopen if you have any issues using commas to separate multiple group object IDs.

**Closed by psignoret** 2016-04-06 02:59 UTC
Labels: bug, question

**Comment by psignoret** [comment] 2016-04-06 03:13
Apologies, I just realized I hadn't actually pushed the changes to GitHub. I have done so now. You can "upgrade" by just replacing the plugin files with the latest.

**Comment by richthomsen** [comment] 2016-04-06 15:07
I added two groups, separated by commas, and it appears to work, thanks!
