### ISSUE TITLE
Prep for WordPress plugin directory

### ISSUE THREAD

**Issue by bradkovach** [psignoret/aad-sso-wordpress#60] opened 2016-02-28 19:33 UTC
I have found the following helpful resources for prepping a plugin for the plugin directory

- http://jeremypry.com/wordpress-plugin-development-with-github/
- https://wordpress.org/plugins/about/
- https://wordpress.org/plugins/about/guidelines/

Todo...
- [ ] Create README.txt
- [ ] Logo?
- [ ] GitHub <-> WordPress SVN sync mechanism

The current version of the plugin in the WP plugin directory is from a Subversion repository (assigned by wordpress.org), so an automated way to push commits from GitHub to Subversion would be nice.  This service seems to handle the process nicely: http://ship.getherbert.com/  If we don't want a third party service, building our own Git<->SVN plugin sync shouldn't be too hard.  GitHub Webhooks would make this totally automatic.

**Comment by psignoret** [comment] 2016-02-28 19:40
Thanks, this is useful.

I'm closing this issue, as it's effectively a duplicate of items tagged for `1.0.0` (which is the release for the WordPress plugin directory). I did add an issue for the README.txt, which I'm in the process of writing.

GitHub > SVN can come for a later release.

**Closed** 2016-02-28 19:40 UTC
